CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE IF NOT EXISTS recipes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  why_it_works TEXT,
  ingredients JSONB,
  instructions JSONB,
  prep_time INT,
  cook_time INT,
  total_time INT,
  servings INT,
  difficulty TEXT,
  cuisine TEXT,
  appliance TEXT,
  category TEXT,
  dietary_tags TEXT[],
  allergens TEXT[],
  nutrition JSONB,
  chef_tips TEXT[],
  substitutions JSONB,
  storage TEXT,
  reheating TEXT,
  faqs JSONB,
  image_url TEXT,
  image_meta JSONB,
  seo_title TEXT,
  seo_description TEXT,
  language TEXT DEFAULT 'en',
  status TEXT DEFAULT 'published',
  generation_date TIMESTAMPTZ DEFAULT NOW(),
  published_at TIMESTAMPTZ DEFAULT NOW(),
  claude_model TEXT,
  meta_image_model TEXT
);
CREATE TABLE IF NOT EXISTS generation_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recipe_id UUID REFERENCES recipes(id),
  generation_date DATE DEFAULT CURRENT_DATE,
  category TEXT,
  cuisine TEXT,
  appliance TEXT,
  dietary_type TEXT,
  language TEXT DEFAULT 'en',
  status TEXT DEFAULT 'published',
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_history_date ON generation_history(generation_date);
